"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowRight, Sparkles } from "lucide-react";
import { toast } from "sonner";
import { StepShell } from "@/components/onboarding/step-shell";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { useOnboardingDraft } from "@/hooks/use-onboarding-draft";
import { useCompleteOnboarding } from "@/hooks/use-complete-onboarding";
import { useOnboardingAccountGate } from "@/hooks/use-onboarding-account-gate";

export default function ProfileStep() {
  const router = useRouter();
  const draft = useOnboardingDraft();
  const mutation = useCompleteOnboarding();
  const gate = useOnboardingAccountGate();
  const [isFinishing, setIsFinishing] = useState(false);
  const isSaving = mutation.isPending || isFinishing;

  useEffect(() => {
    if (isFinishing) return;
    if (!draft.hasHydrated) return;
    if (!gate.canContinue) return;
    if (!draft.frequency) router.replace("/onboarding/frequency");
    else if (!draft.struggles?.length) router.replace("/onboarding/struggles");
    else if (!draft.preferredTime) router.replace("/onboarding/time");
    else if (!draft.motivation) router.replace("/onboarding/motivation");
  }, [
    draft.frequency,
    draft.hasHydrated,
    draft.motivation,
    draft.preferredTime,
    draft.struggles?.length,
    gate.canContinue,
    isFinishing,
    router,
  ]);

  async function handleStart() {
    if (!draft.hasHydrated) return;
    if (!gate.canContinue) {
      router.replace("/onboarding/account");
      return;
    }
    if (!draft.frequency) {
      router.replace("/onboarding/frequency");
      return;
    }
    if (!draft.struggles?.length) {
      router.replace("/onboarding/struggles");
      return;
    }
    if (!draft.preferredTime) {
      router.replace("/onboarding/time");
      return;
    }
    if (!draft.motivation) {
      router.replace("/onboarding/motivation");
      return;
    }
    setIsFinishing(true);
    try {
      await mutation.mutateAsync({
        frequency: draft.frequency,
        struggles: draft.struggles ?? [],
        preferredTime: draft.preferredTime,
        motivation: draft.motivation,
      });
      router.replace("/home");
      draft.reset();
    } catch {
      setIsFinishing(false);
      toast.error("Something didn't save. Try again.");
    }
  }

  return (
    <StepShell step={7} total={7}>
      <div className="flex flex-1 flex-col">
        <div className="flex-1 space-y-6">
          <div>
            <p className="text-xs font-medium uppercase tracking-wider text-muted-foreground">
              Final step
            </p>
            <h1 className="mt-2 font-serif text-3xl leading-tight tracking-tight">
              Let&apos;s build your path.
            </h1>
          </div>
          <Card className="bg-gradient-to-b from-accent/[0.08] to-transparent p-6">
            {isSaving ? (
              <div className="space-y-4">
                <Skeleton className="h-4 w-28" />
                <Skeleton className="h-9 w-3/4" />
                <Skeleton className="h-5 w-full" />
                <div className="space-y-2 rounded-lg border border-border/70 bg-background/60 p-4">
                  <Skeleton className="h-4 w-40" />
                  <Skeleton className="h-4 w-full" />
                  <Skeleton className="h-4 w-5/6" />
                </div>
              </div>
            ) : (
              <>
                <div className="flex items-center gap-2 text-accent">
                  <Sparkles className="size-4" aria-hidden />
                  <span className="text-xs font-semibold uppercase tracking-wider">
                    Backend-personalized
                  </span>
                </div>
                <p className="mt-3 font-serif text-2xl leading-tight">
                  QuranFlow will shape your plan from your answers.
                </p>
                <p className="mt-3 text-sm leading-relaxed text-muted-foreground">
                  Your profile, reading target, and daily rhythm will be saved to
                  your account.
                </p>
              </>
            )}
          </Card>
          <p className="text-sm leading-relaxed text-muted-foreground">
            Your profile is generated by the backend and can adapt as you read,
            reflect, and return.
          </p>
        </div>
        <Button
          size="xl"
          className="w-full"
          disabled={isSaving || !gate.canContinue}
          onClick={handleStart}
        >
          {isSaving ? "Setting up..." : "Begin my journey"}
          <ArrowRight className="size-4" aria-hidden />
        </Button>
      </div>
    </StepShell>
  );
}
